w3c/wot-architecture

index.html

This PR cleans up the ReSpec data, adds more editor/author information, fixes Issue #20, and simplifies the "Status of This Document" text, while fixing also #21.
[HTML diff](https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fw3c.github.io%2Fwot-architecture%2F&doc2=https%3A%2F%2Fraw.githubusercontent.com%2Fmkovatsc%2Fwot-architecture%2Ffixed-preamble%2Findex.html)

Fixed preamble

---

index.html

Merging various commits and fixes that were in flight from different people.  Revising Ed notes to point to repo (for now, in w3c/wot/security-privacy) where we intend to put some centralized content.
note: I also added anchor tags to some sections and fixed a broken hyperlink using these tags.  These changes do not affect the rendering.

Security refinements

---

index.html

Creating PR against main architecture based on last week's decision on where to host WoT Runtime security reccomendations

Adding WoT runtime risks to S&P section

---

index.html

Based on Issue #85, I update CSS and other link problems.
Currently, following problems are exist:
- a dangling link in [Servient Implementation](https://w3c.github.io/wot-architecture/#servient-implementation).  I think it will be resolved when Issue #88 and #83 is closed.
- a lot of 'Normative references in informative sections are not allowed.'   The warnings are only displayed when using Firefox.  I think this is a problem of ReSpec.

non-obtrusive style for dfn links, and some link related corrections.

---

index.html

The new building blocks was defined as common functions and structure as a result of the consideration of Use cases and 5.2 high-level architecture. Therefore how to inter-connect among servients should be decribed in the same section of "6. WoT Building Blocks".
On the other hands, the section 8 can be focused to the deployments in the actual situation. For example, "8.5 Devices in a Local Network Controlled from a Cloud" and "8.6 Service-to-Service across multiple Domains" are typical cases in the commercial IoT systems.

Add 6.5 Inter connection of servients

---

index.html

PR for Issue #111. 
To make consistent with [Terminology](https://w3c.github.io/wot-architecture/#dfn-application), I change section title to 'Native platform API'.

Add '8.1.1 Native'

---

index.html

Section structure in Use Case section is broken.  It cause section numbering change on later section, and it may cause confusion on discussions.
- [Agriculture](https://w3c.github.io/wot-architecture/#sec-agriculture) and other application domain: 4.x -> should be 4.1.y
- [Common Patterns](https://w3c.github.io/wot-architecture/#commonusecasespatterns): 5. -> should be 4.2
- [Summary](https://w3c.github.io/wot-architecture/#summary): 6 -> should be 4.3
and also I fix some minor problem:
- duplicated id for Connected Car section
- missing `<p>` on Legacy Devices section

[Editorial] fix for Use Case section

---

index.html

cleanup terminology
https://github.com/w3c/wot-architecture/issues/83
moving chapter 7.5 Interconnection of servients to chapter "9 WoT Deployments"
https://github.com/w3c/wot-architecture/issues/110

fixing terminology section

---

proposals/WoT Architecture Explainer.md

Ready to Merge
TD-specific content moved to the TD explainer is deleted from the Architecture explainer in this PR to avoid redundancy.
1. Remove JSON-LD 1.0 TD design alternative

Remove TD-specific content from explainer

---

index.html

Resolves https://github.com/w3c/wot-architecture/issues/108.   Actually I added informative references to three ontologies: SAREF, iot.schema.org, and W3C's SSN.   I could add others (eg OGS O&M) but three is good enough, I think.   I think just one reference (eg to iot.schema.org) does not give readers a good enough idea of the potential variety.

Add references to some useful ontologies (#108)

---

index.html
proposals/TAG review request.md
proposals/security_and_privacy.md

Ready for review/merging
- Small updates to the TAG submission request, but then a big new document, the answers to the security and privacy questionnaire.   Some of these answers are related to the WoT Scripting and WoT Thing Description... I think it might be easier for everyone just to have one document for ALL WoT documents rather than trying to do one for each.
- I may also update some of the Security and Privacy considerations.  
- In particular I think it might also be useful to have a "Scope" section somewhere.  In particular, I say 
certain things are out of scope, like provisioning of keys, but the discussion of LCM in the architecture 
doc seems to imply otherwise.   It would be safer to limit the scope of the WoT Architecture to the 
"operational" phase and NOT make it a …

TAG submission documents

---

proposals/TAG review request.md
proposals/security_and_privacy.md

At our Security TF call on Monday, March 25 we made some edits to our responses to the Security and Privacy Questionnaire, but did not update the version submitted for TAG review. I've created this PR to review the changes.
This replaces https://github.com/w3c/wot-architecture/pull/184 (basically, I branched master into TAG-review-updates so that other unrelated updates to the master would not affect this update).   **I will delete this branch once this PR is merged; the purpose of the TAG-review-updates branch is just to stage updates like this, not to serve as another review target.**

Updates to Security and Privacy Questionnaire

---

index.html

It was pointed out to me that since the wot-security-best-practices and wot-security-testing-plan have not been published as official W3C documents the normal ReSpec auto-lookup mechanism would not work and the current W3C links explicitly included in the document were also broken (returning 404s).   It is also a irregular that we refer to the TD, BT, and SA specs using URLS pointing at github.
This patch:
- Refers to the editor's drafts (heads of the master branches) for wot-security-best-practices and wot-security testing-plan
- Uses respec lookup for the published version of wot-security as well as wot-thing-description, wot-binding-templates and wot-scripting-api
- Adds a reference (inside an ednote paragraph) to the TD review version of wot-thing-description
- Updates the links to …

Fix references to unpublished security drafts and TAG TD spec

---

index.html

We had a workshop with IETF people to check the compatibility of the definitions around affordances, hypermedia controls, etc.
We worked out a good model, but noticed that the definitions of many terms had drifted toward wrong statements.
This PR provides corrections and removes some terminology entries that are unneeded (e.g., terms that are never used in the document). 
There needs to be another PR that updates the longer definitions under Section 6. We also made some action items to align properly in the TD document.
Another identified issue is the new text on "Wot Servients" in Section 6.1, the use of "WoT Client/Server **role**", and the confusion of Servient and intermediary.

Terminology review with IETF

---

index.html

First step to fix #188 
Looking closer it turned out that we do not need a new Section 6.2, but the high-level view of Things, Consumers, and Intermediaries can be part of 6.1 Overview.
The "system configurations" are now 6.10.

Move Section 6.2 to the end of 6

---

index.html

This is work in progress.
Section 6.1 already contains new text to define Things and Consumers independent from client/server roles.
The change also includes regrouping to reflect clarifications around Interaction Affordances, Hypermedia Controls, and Protocol Bindings as discussed during the joint IETF workshop.
The section for system components introducing Servients is now 6.7 (for @takuki and @mryuichi )

Revision of Section 6 to reflect Things and Consumers

---

index.html

In last paragraph of Abstract:
> Overall, the goal is to preserve and support existing security mechanisms and properties. In general, W3C WoT is designed to describe what exists rather than to prescribe what to implement.
"Describe, don't prescribe" is a principle of WoT, not restricted to security.
To emphasize this, this PR updates a first sentence of the paragraph.

emphasize 'Describe, don't prescribe' in Abstract

---

index.html

This adds text on descriptions in addition to the Media Type.
It also fixes the "contains" relation between Interaction Affordances and Protocol Bindings.

Fix #197 (Media Type vs Content Type)

---

index.html

In the abstract there is a mention to "concrete deployment scenarios" as follows.
> The architecture can be mapped onto a variety of concrete deployment scenarios, several examples of which are given.
The above was changed to:
> The architecture can be mapped onto a variety of concrete deployment scenarios, several example **patterns** of which are given.

Editorial fix for Issue #204

---

index.html

In the abstract, there is a phrase "WoT network components".
This was changed to "devices".

(Editorial) "WoT Network Components" to "devices" (Issue #205) 

---

index.html

In the abstract there is a mention to "concrete deployment scenarios" as follows.
> The architecture can be mapped onto a variety of concrete deployment scenarios, several examples of which are given.
The above was changed to:
> The architecture can be mapped onto a variety of concrete deployment scenarios, several example **patterns** of which are given.

(Editorial) "patterns" of concrete deployment scenarios (Issue #204) 

---

index.html

It should cite a paper that pioneered the concept of WoT.
Here is a [link](https://cdn.staticaly.com/gh/w3c/wot-architecture/07e61645229de96b7e1a89845d37b136f4a67e1e/index.html?env=dev#acknowledgments) to the new Acknowledgement section.
@mkovatsc , please make an advice.

Moved the historical information to the acknowledgement (Issue #206)

---

index.html

Mark up all RFC2119 assertions so they can be recovered to generate an implementation report.
A few assertions have been reworded to avoid compound sentences or ambiguous pronoun usage.

Mark up all assertions

---

index.html

Move definitions of "Security", "Personally Identifiable Information" and "Privacy" to the Terminology section.  Addresses issue https://github.com/w3c/wot-architecture/issues/275.

Move security definitions to terminology (issue 275)

---

index.html

Addresses issue https://github.com/w3c/wot-architecture/issues/284.   Also a few other editorial changes to avoid using citations as nouns, which is considered bad form (just to the citations to wot-security, there may be others that do this, but we can defer fixing these until after CR, it is an purely editorial issue).

Remove direct refs to sec best practices and testing docs

---

index.html

This fixes #315 and reduces the redundancy between abstract and introduction. Several outdated phrases were updated.

Improve abstract and introduction

---

index.html

Note: This is with regards to a TAG comment https://github.com/w3ctag/design-reviews/issues/355#issuecomment-505228840 from @dbaron. 
This PR, in particular is, about clarifying the difference between JSON and JSON-LD processing of a TD.

Described what JSON-LD additionally brings to processing (Issue #371)

---

index.html

(for issue #380)
- add a sentence for relationship between private security data and configuration.
- use 'security data' instead of 'security metadata'.

Add definition of private security configuration and data

---

index.html

This replaces https://github.com/w3c/wot-architecture/pull/368 (which simply deleted the definitions of Privacy and Security) with a set of new definitions based on ISO standards.
***
<a href="https://pr-preview.s3.amazonaws.com/mmccool/wot-architecture/pull/384.html" title="Last updated on Sep 9, 2019, 10:28 AM UTC (f9bc2ab)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-architecture/384/9aa9dd9...mmccool:f9bc2ab.html" title="Last updated on Sep 9, 2019, 10:28 AM UTC (f9bc2ab)">Diff</a>

Modify security and privacy definitions to refer to ISO standards

---

index.html

Rename section headings for https://github.com/w3c/wot-architecture/issues/392
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/wot-architecture/pull/394.html" title="Last updated on Oct 11, 2019, 4:50 AM UTC (a8f5462)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-architecture/394/4a1fcb0...a8f5462.html" title="Last updated on Oct 11, 2019, 4:50 AM UTC (a8f5462)">Diff</a>

Update index.html - rename section headings

---

index.html

NOTE: all changes here included in https://github.com/w3c/wot-architecture/pull/400
- Reword opening paragraph of deployment section to emphasize that these are non-normative examples
- Add a short discussion of privacy right after the introduction of TD discovery and distribution
- Small tweaks to opening of Security and Privacy section
NOTE: originally I did these edits to try to address PLH's concern about mentioning the ID risk, BUT then I realized there would be merge conflicts due to the whole private security data/Private Security Data change, which was still pending.
I therefore created https://github.com/w3c/wot-architecture/pull/400 to merge these changes with the Private Security Data changes... if that PR is merged, this PR should be closed without merging since all the …

Add privacy paragraph to "Deployment" section

---

index.html

NOTE: all changes here included in https://github.com/w3c/wot-architecture/pull/400
Add definitions for the following terms to the Terminology section:
- Private Security Data
- Public Security Metadata
Also add the following terms used by the above:
- Metadata
- Security Configuration
Also various changes through the document to mark up these terms where they appear to link back to the definition.
***
<a href="https://pr-preview.s3.amazonaws.com/mmccool/wot-architecture/pull/396.html" title="Last updated on Oct 17, 2019, 5:28 AM UTC (534c223)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-architecture/396/4a1fcb0...mmccool:534c223.html" title="Last updated on Oct 17, 2019, 5:28 AM UTC (534c223)">Diff</a>

Update index.html - Add security data/metadata defns

---

index.html

Small fixes:
- Remove normative like to RFC8288 from now-informative Terminology section
- Note in change log "Make Terminology section informative"
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/wot-architecture/pull/404.html" title="Last updated on Oct 22, 2019, 5:02 AM UTC (8b920ec)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-architecture/404/cb32100...8b920ec.html" title="Last updated on Oct 22, 2019, 5:02 AM UTC (8b920ec)">Diff</a>

Make terminology informative - Update

---

index.html

Moving the basic terms for the stakeholders from the security document
***
<a href="https://pr-preview.s3.amazonaws.com/ereshetova/wot-architecture/pull/418.html" title="Last updated on Dec 23, 2019, 7:39 AM UTC (d766800)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-architecture/418/8b554a6...ereshetova:d766800.html" title="Last updated on Dec 23, 2019, 7:39 AM UTC (d766800)">Diff</a>

Move stakeholder terms from security doc

---

USE-CASES/connected-building-energy-efficiency.md

Here is the use case for the Thing Directory implementation [presented](https://raw.githubusercontent.com/wiki/linksmart/thing-directory/presentations/thing-directory-wot-call-2020-4-15.pdf) in April.
Closes issue #481.

Add smart building energy efficiency use case

---

USE-CASES/retail.md

Merging S&P considerations from Clerley and Conexxus.  Still needs further discussion before merging.

Update retail.md with Security and Privacy considerations

---

index.html

- Add WOT-USE-CASES reference to local references
- Add editor's notes linking to use cases repo and document at start of Application verticals section
- Add editor's note referring to arch repo at start of requirements section (also references use case document)-
- Add citation to WOT-USE-CASES document elsewhere where it was referenced in text (just one place, actually...)
Resolves https://github.com/w3c/wot-architecture/issues/550
Resolves https://github.com/w3c/wot-architecture/issues/549
***
<a href="https://pr-preview.s3.amazonaws.com/mmccool/wot-architecture/pull/560.html" title="Last updated on Oct 6, 2020, 2:16 PM UTC (77da29a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-architecture/560/503d22d...mmccool:77da29a.html" title="Last updated on Oct 6, 2020, …

add links to requirements and Use Case repos and docs

---

REQUIREMENTS/link-relation-types.md

Coming from https://github.com/w3c/wot-testing/issues/87, this PR adds two possible link types to point towards WebThing UIs. See [my comment](https://github.com/w3c/wot-testing/issues/87#issuecomment-702801947)

Add candidates for UI link types

---

index.html

I tried to simplify the definition given during the last call. In particular, I dropped the term _subset of_ because it could be understood as if a Partial TD could contain any element of the TD model without any particular order or structure (much like a TD fragment). I also remove the information about the serialization because I found it redundant.  
@ashimura I linked the scripting API document in the _Note_. Did I use the correct link? Should I refer to the published document or the TR is ok? Sorry, I'm still confused a little bit about the publication process.
***
<a href="https://pr-preview.s3.amazonaws.com/relu91/wot-architecture/pull/577.html" title="Last updated on Jan 19, 2021, 3:14 PM UTC (b939bd5)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-architecture …

Introduce Partial TD definition

---

index.html

all the others seems to be sorted sorted lexicographically
see its current place, https://w3c.github.io/wot-architecture/#dfn-partial-td
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/wot-architecture/pull/590.html" title="Last updated on Apr 22, 2021, 9:59 AM UTC (afaa7f0)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-architecture/590/42655e7...afaa7f0.html" title="Last updated on Apr 22, 2021, 9:59 AM UTC (afaa7f0)">Diff</a>

Move Partial TD definition to right place in list

---

index.html

As discussed in the call of 22.03.2021, this PR moves terminology from binding templates to here
***
<a href="https://pr-preview.s3.amazonaws.com/egekorkan/wot-architecture/pull/586.html" title="Last updated on Mar 22, 2021, 1:31 PM UTC (7fe266c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-architecture/586/c0c8113...egekorkan:7fe266c.html" title="Last updated on Mar 22, 2021, 1:31 PM UTC (7fe266c)">Diff</a>

Add terminology from binding templates

---

index.html

- Add WoT Discovery (local) reference
- Add Discovery definition under "Terminology" and update references elsewhere in the text
- Add content to the Discovery section under "Building Blocks"
Resolves https://github.com/w3c/wot-architecture/issues/557
Updates:
- Add assertions (MUST for *properties* that any TD distribution mechansism must have, SHOULD for recommending use of specfic mechanisms defined in WoT Discovery document)
- Thing Directory -> Thing Description Directory (consistent with WoT Discovery doc, avoid ambiguous acronym)
- Various updates to other discussions of discovery
- Updates to definition (remove suggestion that CoRE-RD can be used; cite WoT Discovery doc, and of course update name)
- Updates to security and privacy considerations to reference doc
- Addition of …

Add Discovery refs, dfn, and section

---

index.html

Resolves https://github.com/w3c/wot-architecture/issues/598
Note: "hub" is only mentioned in this section now and no-where else.  So the definition of hub also needs to be addressed, but this should be dealt with in a different PR that addresses issue https://github.com/w3c/wot-architecture/issues/581
***
<a href="https://pr-preview.s3.amazonaws.com/mmccool/wot-architecture/pull/601.html" title="Last updated on Jul 15, 2021, 1:46 PM UTC (a5dfece)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-architecture/601/af1a8df...mmccool:a5dfece.html" title="Last updated on Jul 15, 2021, 1:46 PM UTC (a5dfece)">Diff</a>

Fixup Device Classes

---

index.html

Provides text for the [TM section](https://w3c.github.io/wot-architecture/#thing-models). 
Copy some [parts](https://w3c.github.io/wot-thing-description/#thing-model-concept) from the TD, which will be removed in one of the next updates.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/wot-architecture/pull/604.html" title="Last updated on Jul 15, 2021, 11:02 AM UTC (36a8c29)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-architecture/604/af1a8df...36a8c29.html" title="Last updated on Jul 15, 2021, 11:02 AM UTC (36a8c29)">Diff</a>

WIP: Provides text for TM

---

index.html

Counterpart to https://github.com/w3c/wot-thing-description/pull/1191 in the Thing Description specification, to add descriptions for the `subscribeallevents` and `unsubscribeallevents` operations, as discussed in https://github.com/w3c/wot-thing-description/issues/1082.
Also adds descriptions for the missing `observeallproperties` and `unobserveallproperties` operations.
***
<a href="https://pr-preview.s3.amazonaws.com/benfrancis/wot-architecture/pull/605.html" title="Last updated on Jul 19, 2021, 1:54 PM UTC (740aadc)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-architecture/605/af1a8df...benfrancis:740aadc.html" title="Last updated on Jul 19, 2021, 1:54 PM UTC (740aadc)">Diff</a>

Add observeallproperties, unobserveallproperties, subscribeallevents and unsubscribeallevents

---

index.html

Implementing precedence rule after discussions in editors call.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/wot-architecture/pull/631.html" title="Last updated on Nov 3, 2021, 12:29 PM UTC (e615cef)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-architecture/631/6531e45...e615cef.html" title="Last updated on Nov 3, 2021, 12:29 PM UTC (e615cef)">Diff</a>

precedence rule for terminology

---

index.html

(Fixes for w3c/wot-architecture#613, w3c/wot-discovery#240): 
Move following terms from Discovery spec to Architecture spec.
- Anonymous TD
- Discoverer
- Exploration
- Introduction
***
<a href="https://pr-preview.s3.amazonaws.com/k-toumura/wot-architecture/pull/644.html" title="Last updated on Nov 30, 2021, 6:52 AM UTC (541f3b6)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-architecture/644/e2a1cfa...k-toumura:541f3b6.html" title="Last updated on Nov 30, 2021, 6:52 AM UTC (541f3b6)">Diff</a>

Move common terms from Discovery to Architecture

---

index.html

(Fixes #647, #648)
Make following sections informative by adding `class="informative"`:
- 1 Introduction
- 4 Device Categories
- 7 System Integration
***
<a href="https://pr-preview.s3.amazonaws.com/k-toumura/wot-architecture/pull/649.html" title="Last updated on Dec 3, 2021, 12:26 AM UTC (719a11e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-architecture/649/e35094d...k-toumura:719a11e.html" title="Last updated on Dec 3, 2021, 12:26 AM UTC (719a11e)">Diff</a>

[Editorial] Make sections informative

---

index.html

I've been assigned to #640. With this PR I'm following the consensus reached of removing the assertion from the document. Notice that I remove the section completely because I wasn't sure to leave it there without a proper assertion.
***
<a href="https://pr-preview.s3.amazonaws.com/relu91/wot-architecture/pull/650.html" title="Last updated on Dec 3, 2021, 9:37 AM UTC (4a42d16)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-architecture/650/1f4a8b8...relu91:4a42d16.html" title="Last updated on Dec 3, 2021, 9:37 AM UTC (4a42d16)">Diff</a>

remove arch-methods assertion and section

---

index.html

(Fixes #636 )
Based on the discussion on Nov. 25, I've removed the assertion `arch-consumer-configuration`.
***
<a href="https://pr-preview.s3.amazonaws.com/k-toumura/wot-architecture/pull/651.html" title="Last updated on Dec 6, 2021, 4:27 AM UTC (9d0e1b1)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-architecture/651/1f4a8b8...k-toumura:9d0e1b1.html" title="Last updated on Dec 6, 2021, 4:27 AM UTC (9d0e1b1)">Diff</a>

Remove `arch-consumer-configuration`

---

index.html

This should only be merged after the TD specification contains a clarification about the handling of uppercase/lowercase vocabulary terms.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/wot-architecture/pull/668.html" title="Last updated on Jan 18, 2022, 7:56 AM UTC (646df83)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-architecture/668/8645973...646df83.html" title="Last updated on Jan 18, 2022, 7:56 AM UTC (646df83)">Diff</a>

remove remove-arch-op-wellknown-compare assertion

---

index.html

represention --> representation
categorisation --> categorization ... used line before with z
"TD Information Model"and section    --> "TD Information Model" and
decomission 	--> decommission
accomodate 	--> accommodate
mimimize 	--> minimize
***
<a href="https://pr-preview.s3.amazonaws.com/danielpeintner/wot-architecture-1/pull/683.html" title="Last updated on Jan 27, 2022, 4:22 PM UTC (24b883f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-architecture/683/737fc23...danielpeintner:24b883f.html" title="Last updated on Jan 27, 2022, 4:22 PM UTC (24b883f)">Diff</a>

fix: some typos

---

index.html

Resolves https://github.com/w3c/wot-architecture/issues/672
WIP: Do not merge, still being reviewed by Security TF
- add trusted environment risk
***
<a href="https://pr-preview.s3.amazonaws.com/mmccool/wot-architecture/pull/686.html" title="Last updated on Feb 2, 2022, 5:37 PM UTC (524e6bb)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-architecture/686/7368123...mmccool:524e6bb.html" title="Last updated on Feb 2, 2022, 5:37 PM UTC (524e6bb)">Diff</a>

Update Security and Privacy Considerations (2)

---

index.html

New definitions for Device, Service, and Shadow.
Updated definitions for Virtual Thing and Digital Twin.
Resolves issue #709.
Resolves issue #708.
***
<a href="https://pr-preview.s3.amazonaws.com/mmccool/wot-architecture/pull/711.html" title="Last updated on Feb 17, 2022, 5:15 PM UTC (14d0d30)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-architecture/711/78521c3...mmccool:14d0d30.html" title="Last updated on Feb 17, 2022, 5:15 PM UTC (14d0d30)">Diff</a>

Definitions for Device, Service, etc.

---

index.html

To resolve the following Respec error, I've added an alternative name to Thing Model definition in "4. Terminology. "

Add `data-lt` to a definition of Thing Model

---

index.html

Fix #716 .
***
<a href="https://pr-preview.s3.amazonaws.com/k-toumura/wot-architecture/pull/721.html" title="Last updated on Mar 11, 2022, 12:52 AM UTC (9c965fe)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-architecture/721/2ceb79e...k-toumura:9c965fe.html" title="Last updated on Mar 11, 2022, 12:52 AM UTC (9c965fe)">Diff</a>

Change "Thing Directory" to "Thing Description Directory"

---

index.html

Fix #719 .
Used ReSpec's [`formerEditors` option](https://github.com/w3c/respec/wiki/formerEditors).
***
<a href="https://pr-preview.s3.amazonaws.com/k-toumura/wot-architecture/pull/720.html" title="Last updated on Mar 11, 2022, 12:30 AM UTC (1490fb1)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-architecture/720/2ceb79e...k-toumura:1490fb1.html" title="Last updated on Mar 11, 2022, 12:30 AM UTC (1490fb1)">Diff</a>

Update list of editors

---

index.html

Resolves #699 
- Links to (new) Architecture IR (still to be created...) in SOTD
- Links to Architecture IR in header, consistent with other docs
- Says that Architecture IR describes implementations following the architecture
- Says that Architecture IR links to other IRs for building blocks
So when we do write the Arch IR, we need to remember to do the last two points.  The alternative would be to link to each of the building blocks' IRs directly from the Architecture SOTD but I think that will just clutter things up.  They are also linked from the header of each document (or should be).
***
<a href="https://pr-preview.s3.amazonaws.com/mmccool/wot-architecture/pull/701.html" title="Last updated on Feb 3, 2022, 2:31 AM UTC (4f83abb)">Preview</a> | <a …

Update Implementation Report link in SOTD

---

index.html

* Resolves https://github.com/w3c/wot-architecture/issues/581
* Resolves https://github.com/w3c/wot-architecture/issues/585
***
<a href="https://pr-preview.s3.amazonaws.com/mmccool/wot-architecture/pull/603.html" title="Last updated on Jul 15, 2021, 4:18 PM UTC (432a5cd)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-architecture/603/af1a8df...mmccool:432a5cd.html" title="Last updated on Jul 15, 2021, 4:18 PM UTC (432a5cd)">Diff</a>
***
<a href="https://pr-preview.s3.amazonaws.com/mmccool/wot-architecture/pull/603.html" title="Last updated on Mar 24, 2022, 10:43 AM UTC (432a5cd)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-architecture/603/af1a8df...mmccool:432a5cd.html" title="Last updated on Mar 24, 2022, 10:43 AM UTC (432a5cd)">Diff</a>

Define and Discuss "Hubs"

---

index.html

- Producer was, in fact, already linked from Security and Privacy, so removed ignore-lint from its dfn
- There was another ReSpec error caused by the latest update to the use case description, a simple missing period, so I fixed that while I was at it
This PR has 0 ReSpec errors.
***
<a href="https://pr-preview.s3.amazonaws.com/mmccool/wot-architecture/pull/733.html" title="Last updated on Apr 7, 2022, 12:09 PM UTC (e5761bd)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-architecture/733/7da670c...mmccool:e5761bd.html" title="Last updated on Apr 7, 2022, 12:09 PM UTC (e5761bd)">Diff</a>

Fix Producer ref and respec error

---

index.html

addresses this point in issue #672 - makes consistent with other deliverables (Discovery and TD 1.1)
- mark both Security Considerations and Privacy Considerations sections as normative
- update change log
- remove "refactoring" ed note (actually resolved a long time ago)
- add assertion spans and RFC2119 keywords to normative mitigations
- some rewording needed to make the above possible in some cases
Given the timing and the cancellation of Architecture calls over the next two weeks, we will review and revise these in the Security TF and based on PR reviews aiming for a final version by end of April so we can hit the normative feature freeze deadline of May 6.  Unfortunately some of the text does needs revision for the assertions to make sense as standalone sentences and not be …

Make Security and Privacy Considerations Normative

---

index.html

Fixes #743 
I have also removed it from the rel keyword
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/wot-architecture/pull/749.html" title="Last updated on May 12, 2022, 8:44 AM UTC (367ed01)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-architecture/749/7be810a...367ed01.html" title="Last updated on May 12, 2022, 8:44 AM UTC (367ed01)">Diff</a>

Remove abnf validation from rel and op

---

index.html

resolves https://github.com/w3c/wot-architecture/issues/675
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/wot-architecture/pull/760.html" title="Last updated on May 19, 2022, 10:17 AM UTC (a35986f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-architecture/760/36ad1c9...a35986f.html" title="Last updated on May 19, 2022, 10:17 AM UTC (a35986f)">Diff</a>

changing section level for MediaTypes

---

index.html

Resolves Issue #635 
Relevant to Issue #625
- delete arch-id-correlation assertion
- adjust text immediately before, which I think was written when we were constraining Things to represent *physical* entities, and implied an Intermediary was not a Thing, but "like" a Thing.  I changed this to say an Intermediary is a "kind of" Thing, and also changed the phrase "virtual entity" to "Virtual Thing" since we have a consistent definition for that now.
ASIDE: the "[big discussion](https://github.com/w3c/wot-discovery/issues/190)" in discovery was actually about whether the ID refers to the TD (as a document) or to the Thing being described by the TD.   In other words, do we identify the map or the territory? If we choose the latter interpretation, AND insist that only physical entities can be …

Remove arch-id-correlation assertion

---

index.html

(related issue/PR: #628, #771)
I didn't notice in on the Arch call in May 24th, some structure of section seems broken.
There is extra `</section>` tag on after "5.9 Virtual Things": https://github.com/w3c/wot-architecture/blob/02b9aeaf3cffe29b72c4522362c9380aca5c2eb3/index.html#L1568-L1571
This extra tag accidentally makes the subsequent "Cross-domain Collaboration" and "System Integration" subsection independent from the Section 5 "Common Deployment Patterns".
This PR remove the extra section tag, and also remove introduction text for "Cross-domain Collaboration" and "System Integration" (and also fix section ID).   The resulting section structure is as follows:
```
...
5. Common Deployment Patterns
5.1 Telemetry
...
5.9 Virtual Things
5.10 Cross-domain Collaboration
5.11 System …
```

Fix section structure error (6. Cross-domain Collaboration, 7. System Integration)

---

index.html

Resolves #753 
- remove two generallys
- SHOULD use TLS 1.3
- MAY use TLS 1.2
- SHOULD use DTLS 1.3
- MAY use TLS 1.2
- MUST not use earlier versions of TLS or DTLS for new development (as opposed to describing brownfield devices)
- RFC references for the above
***
<a href="https://pr-preview.s3.amazonaws.com/mmccool/wot-architecture/pull/783.html" title="Last updated on Jun 30, 2022, 10:01 AM UTC (77a9070)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-architecture/783/af14f99...mmccool:77a9070.html" title="Last updated on Jun 30, 2022, 10:01 AM UTC (77a9070)">Diff</a>

Specify TLS and DTLS versions

---

index.html

adding reference to ASCII case insensitive definition of whatwg.
Resiolves issue #775
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/wot-architecture/pull/795.html" title="Last updated on Jul 4, 2022, 8:22 PM UTC (5dc9f94)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-architecture/795/0b1117c...5dc9f94.html" title="Last updated on Jul 4, 2022, 8:22 PM UTC (5dc9f94)">Diff</a>

Address feedback from i18n group

---

index.html

The changelog has been already published in the latest WD and unfortunately was not merged to the main branch.
https://www.w3.org/TR/2022/WD-wot-architecture11-20220907/#changes
This PR restores it.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/wot-architecture/pull/832.html" title="Last updated on Sep 8, 2022, 2:52 PM UTC (c61671a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-architecture/832/2d1f901...c61671a.html" title="Last updated on Sep 8, 2022, 2:52 PM UTC (c61671a)">Diff</a>

restoring changelog

---

index.html

Adding 2 references to the published use case document.
Resolves issue #802
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/wot-architecture/pull/840.html" title="Last updated on Sep 22, 2022, 9:58 AM UTC (0fd32c8)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-architecture/840/df6692c...0fd32c8.html" title="Last updated on Sep 22, 2022, 9:58 AM UTC (0fd32c8)">Diff</a>

Add 2 references to the published use case document - Resolves #802

---

index.html

Implement the proposal from TD issue #1719
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/wot-architecture/pull/865.html" title="Last updated on Oct 25, 2022, 9:40 AM UTC (7c519c0)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-architecture/865/efb4cf6...7c519c0.html" title="Last updated on Oct 25, 2022, 9:40 AM UTC (7c519c0)">Diff</a>

Adding terminology "WoT Profile"

---

index.html

this is an alternative PR to #862
Since there are no normative assertions in this chapter, there is no reason to define the whole section as normative.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/wot-architecture/pull/871.html" title="Last updated on Nov 2, 2022, 10:54 AM UTC (41f89d7)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-architecture/871/8cdbb9e...41f89d7.html" title="Last updated on Nov 2, 2022, 10:54 AM UTC (41f89d7)">Diff</a>

Option 2: Define whole Chapter 7 non-normative

---

index.html
publication/ver11/3-cr/Overview.html
publication/ver11/3-cr/index.html
publication/ver11/3-cr/static.html
testing/report11.html

As agreed, this PR downgrades sections 7.4 and 7.5 to informative sections, removing any assertions.  This allows the entirely of section 7 to be informative as previously decided.  It also makes a few other necessary changes consistent with this goal.  Details:
- Small change to the abstract that outlines the sections, which previously said both section 6 and section 7 were normative.   Now it only says section 6 is normative.  
- NOTE: a section outline does NOT belong in the abstract, for the same reason we can't have references in the abstract: the abstract needs to be self-contained.  The section outline in particular has hyperlinks which would be broken if the abstract is used out of content.
- I would prefer we delete this list, or move it to the intro (although the intro ALSO has …

Remove Section 7 assertions

---

index.html

Adding change log for updates since WD published September 7.   I went through the closed PRs and extracted what I felt were the major changes.  This includes the change to make Section 7 informative.
NOTE: I also noticed and fixed a minor markup problem with one of the citations to the use cases document.
***
<a href="https://pr-preview.s3.amazonaws.com/mmccool/wot-architecture/pull/875.html" title="Last updated on Nov 3, 2022, 1:21 PM UTC (f0c0f44)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-architecture/875/1c7ba10...mmccool:f0c0f44.html" title="Last updated on Nov 3, 2022, 1:21 PM UTC (f0c0f44)">Diff</a>

Change Log for updates from WD 2022-09-07

---

index.html

this is required for the CR request https://github.com/w3c/transitions/issues/474
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/wot-architecture/pull/878.html" title="Last updated on Nov 16, 2022, 12:59 PM UTC (f55abaf)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-architecture/878/5f788cc...f55abaf.html" title="Last updated on Nov 16, 2022, 12:59 PM UTC (f55abaf)">Diff</a>

Provide CR exit statment in sotd section

---

index.html

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/wot-architecture/pull/879.html" title="Last updated on Nov 21, 2022, 2:53 PM UTC (c3b05fc)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-architecture/879/3c0e8b8...c3b05fc.html" title="Last updated on Nov 21, 2022, 2:53 PM UTC (c3b05fc)">Diff</a>

Fix broken link for respec

---

index.html

solves binding reference issue as mentioned here https://github.com/w3c/transitions/issues/474#issuecomment-1320565680
The change log section includes a normative reference to the binding template document, however, which should be a non-normative reference. This PR fixes this.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/wot-architecture/pull/880.html" title="Last updated on Nov 23, 2022, 10:18 AM UTC (01a0836)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-architecture/880/3c0e8b8...01a0836.html" title="Last updated on Nov 23, 2022, 10:18 AM UTC (01a0836)">Diff</a>

fix binding reference in change log

---

index.html

Resolves #900.
Resolves #908 
- Remove at-risk assertion arch-security-consideration-use-psk
- Keep statement, but downgrade (SHOULD -> should) to an informative statement
- Address Issue #900 by using "certificates" instead of "pre-shared keys"
- Edit some of the following text to more clearly differentiate between the roles of certificates (which prove identity) and other security materials (like API keys or passwords) that are used for access control.
- Since it was an adjacent issue, also resolve #908 about guest networks
***
<a href="https://pr-preview.s3.amazonaws.com/mmccool/wot-architecture/pull/909.html" title="Last updated on May 17, 2023, 5:20 PM UTC (10e9df5)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-architecture/909/476a18f...mmccool:10e9df5.html" …

Resolve arch-security-consideration-use-psk

---

index.html

Resolves #903
- Remove at-risk assertion arch-security-consideration-dtls-1-3
- Keep statement, but downgrade (SHOULD -> should) to an informative statement
- Nothing else changed.  Because of parallel structure however this looks a little like a mistake, but it is technically correct.
***
<a href="https://pr-preview.s3.amazonaws.com/mmccool/wot-architecture/pull/910.html" title="Last updated on May 18, 2023, 10:20 AM UTC (55916c4)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-architecture/910/476a18f...mmccool:55916c4.html" title="Last updated on May 18, 2023, 10:20 AM UTC (55916c4)">Diff</a>

Resolve arch-security-consideration-dtls-1-3

---

index.html

Resolves #905
- Remove at-risk assertion arch-security-consideration-hal-refuse-unsafe
- Keep statement, but downgrade (SHOULD -> should) to an informative statement
- Add informative text explaining what a HAL is and mentioning some implementation options (addresses issue #905)
- Add informative text stating that HAL-based software interlocks should not be the only safety measure
***
<a href="https://pr-preview.s3.amazonaws.com/mmccool/wot-architecture/pull/911.html" title="Last updated on May 18, 2023, 10:36 AM UTC (43ff2d9)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-architecture/911/476a18f...mmccool:43ff2d9.html" title="Last updated on May 18, 2023, 10:36 AM UTC (43ff2d9)">Diff</a>

Resolve arch-security-consideration-hal-refuse-unsafe

---

index.html

fix another instance of native in HAL section
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/wot-architecture/pull/915.html" title="Last updated on May 22, 2023, 12:33 PM UTC (e0d4a37)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-architecture/915/f37bc2a...e0d4a37.html" title="Last updated on May 22, 2023, 12:33 PM UTC (e0d4a37)">Diff</a>

Fix another instance of "native"

---

index.html

Resolves #804 
Uplevel profile section - avoid mentioning specific profiles
- Comment out section that mentions HTTP Baseline Profile, SSE Profile, etc - not yet decided.
- Add Note that WoT Profiles is still a Working Draft.
- Change Image caption to just "Profile architecture" so it does not seem like we are defining the term "WoT Baseline" as a thing - "a baseline profile" is used only as a generic category in the text.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/wot-architecture/pull/917.html" title="Last updated on May 25, 2023, 10:32 AM UTC (a961865)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-architecture/917/9744a3f...a961865.html" title="Last updated on May 25, 2023, 10:32 AM UTC (a961865)">Diff</a>

Uplevel Profile Section

---

index.html

Resolves #578 
- Initial draft based on outline provided in issue
- Added appropriate specref references
- Reference to W3C Web Content Accessibility Guidelines updated to version 2.2 published May 2023
- Due to the timing, this has to be an informative section.
WIP as we have several points to resolve, including: 
- use of the term "manifest" (resolved, but to discuss)
- distinction between kinds of user interfaces (on-device, web) (resolved)
- use of third-party systems to provide interfaces. (resolved)
- Assertive language is used ("must", etc) but this may have to be tempered as this is an informative section. (still exists, but not a big point - except for cases where "best effort" is needed, i.e. it's hard to make a 1" display accessible)
***
<a …

Add Accessibility Considerations

---

errata/v11.md
errata11.html
index.html
publication/ver11/5-rec/Overview.html
publication/ver11/5-rec/index.html
publication/ver11/5-rec/static.html

- Update to use HTML errata template
- HTML tidy run, all errors fixed
- [HTML Checker](https://validator.w3.org/nu/?doc=https%3A%2F%2Fw3c.github.io%2Fwot-architecture%2Fpublication%2Fver11%2F5-rec%2FOverview.html)
- The type attribute for the style element is not needed and should be omitted. (fixed)
- [CSS Checker](https://jigsaw.w3.org/css-validator/validator?uri=https%3A%2F%2Fw3c.github.io%2Fwot-discovery%2Fpublication%2F6-rec%2FOverview.html&profile=css3svg&usermedium=all&warning=1&vextwarning=&lang=en)
- minor warning for included style sheet (ignored): https://www.w3.org/StyleSheets/TR/2021/base.css
- [Link checker](https://validator.w3.org/checklink?uri=https%3A%2F%2Fw3c.github.io%2Fwot-architecture%2Fpublication%2Fver11%2F5-rec%2FOverview.html&hide_type=all&depth=&check=Check): …

REC Preparation v2
