index.html
Some suggested updates to the abstract.   Some of these are cleanups to the English, however others are to clarify the "descriptive vs. prescriptive" purpose of the WoT.   I also explictly mention the building block deliverables.
Let's discuss.   I think the abstract needs a lot of work and since it's the very first thing people will read, it's important to get it right.
=> Suggested updates to abstract

index.html
Initial proposals for security sections in architecture document.   Plenty of room for criticism and comment, so fire away.
=> Security architecture sections

index.html
A bunch of changes aimed at cleaning up formatting and English.   These changes DO NOT touch the security and abstract sections in the other two pending pull requests to avoid conflicts.
I have tried to avoid substantive changes in this pull request and aimed only at clarifying the language.  Unfortunately, I think there are some issues around terminology (WoT Servient vs Thing, for instance) that need to be brought into consensus with the rest of the group...
=> Clean up formatting and English

proposals/requirements.md
As same as e-mailed to arch editors.
=> Create proposals folder and submit straw-man of new requirements section

index.html
Just editorial corrections. 
Some references to figure have been removed by commit 4d55044.  This PR recovers them.
=> Recover references to figure

proposals/WoT Architecture - Explanation for TAG review.md
=> Explainer - Building Blocks Section

index.html
=> Add text on accessibility

index.html
The edge word is missing in the sentence, otherwise, this sentence does not make sense.
=> 'edge' is missing

index.html
Updates to the terminology changes as discussed on 5.4.
=> Terminology updates

index.html
=> Fix #233 (no exact number of schemas in Affordances)

index.html
Aligned section 9 with improved section 6.
=> Aligned section 9 with improved section 6 (for issue #216)

index.html
=> Added references to pioneering WoT works.

index.html
=> Remove Application definition from Terminology

index.html
=> Hypermedia Controls examples (Fix #236 and #246)

index.html
This is per comments in PR #263.
=> Modifying the title of section 9.2

index.html
- Add basic changed log (needed for CR transition)
- Add Klaus Hartke
- Make titles and ordering of change log and acknowledgements consistent with TD
=> Add change log

index.html
I've  checked the diffs between the [master branch version](https://w3c.github.io/wot-architecture/)  and the [CR published version](https://www.w3.org/TR/2019/CR-wot-architecture-20190516/Overview.html) and generated a pullrequest to apply the changes.
Note that some of the edits can't be applied to the master branch version due to ReSpec's restriction, we still need some minor edit when we publish a Proposed Recommendation.
=> apply feedback from the CR version

index.html
Added a definition for Data Schema.
***
<a href="https://pr-preview.s3.amazonaws.com/takuki/wot-architecture/pull/383.html" title="Last updated on Sep 5, 2019, 5:20 AM UTC (25a9a2b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-architecture/383/ab4ea36...takuki:25a9a2b.html" title="Last updated on Sep 5, 2019, 5:20 AM UTC (25a9a2b)">Diff</a>
=> Defined Data Schema in Terminology section.

index.html
Reword private security metadata / configurations
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/wot-architecture/pull/385.html" title="Last updated on Sep 12, 2019, 7:19 AM UTC (495a88e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-architecture/385/43eeb31...495a88e.html" title="Last updated on Sep 12, 2019, 7:19 AM UTC (495a88e)">Diff</a>
=> Clarify terminology - security configuration / data

index.html
Additional clarifications in the introduction section to address 
https://github.com/w3c/wot-architecture/issues/391
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/wot-architecture/pull/395.html" title="Last updated on Oct 11, 2019, 4:51 AM UTC (ee83982)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-architecture/395/4a1fcb0...ee83982.html" title="Last updated on Oct 11, 2019, 4:51 AM UTC (ee83982)">Diff</a>
=> Update index.html - Introduction

index.html
to resolve my proposed [Issue 402](https://github.com/w3c/wot-architecture/issues/402), I'd suggest we merge this pullrequest.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/wot-architecture/pull/403.html" title="Last updated on Oct 21, 2019, 1:59 PM UTC (cb32100)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-architecture/403/b7a6cbc...cb32100.html" title="Last updated on Oct 21, 2019, 1:59 PM UTC (cb32100)">Diff</a>
=> make terminology section informative

index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/wot-architecture/pull/407.html" title="Last updated on Oct 23, 2019, 11:32 AM UTC (abca353)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-architecture/407/8620f5c...abca353.html" title="Last updated on Oct 23, 2019, 11:32 AM UTC (abca353)">Diff</a>
=> Details about reference changes to the change log.

index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/wot-architecture/pull/419.html" title="Last updated on Jan 8, 2020, 3:45 PM UTC (7fe03a1)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-architecture/419/fb52f61...7fe03a1.html" title="Last updated on Jan 8, 2020, 3:45 PM UTC (7fe03a1)">Diff</a>
=> update eventSource reference to HTML

index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/wot-architecture/pull/439.html" title="Last updated on Feb 20, 2020, 6:57 AM UTC (1ac3c8f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-architecture/439/51c91bf...1ac3c8f.html" title="Last updated on Feb 20, 2020, 6:57 AM UTC (1ac3c8f)">Diff</a>
=> Minor editorial changes to address #1 and #2 of https://github.com/w3c/wot-architecture/issues/437

REQUIREMENTS/requirements-template.md, USE-CASES/use-case-template.md
- Add "Security Considerations" and "Privacy Considerations" sections to use case template
- Add "Security" and "Privacy" sub-sections under "Requirements" in requirements template
See: https://github.com/w3c/wot-architecture/issues/472
TO DO: go through and update all existing use cases and requirements to include these sections.  This can be done in a followup PR.
=> Propose new use-case and requirement template sections for security and privacy

proposals/lifecycle-model-proposal-zolkis.md
=> Add device lifecycle proposal

USE-CASES/README.md, USE-CASES/smart-building.md
Provide smart building use case
=> Add smart building use case

USE-CASES/MedicalDevices.md
Initial draft of medical device use case.
=> Created Medical Devices use case

USE-CASES/oauth.md
Re-submitting #515 to clear IPR.
=> Update oauth2.0 use cases

REQUIREMENTS/discovery.md
To support the WoT Discovery deliverable.
=> Define Discovery requirements

REQUIREMENTS/agriculture-greenhouse.md, REQUIREMENTS/agriculture.md
Regenerate agriculture requirements based on 3.9 discussion.
=> Agriculture (greenhouse horticulture) requirements

index.html
see subject
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/wot-architecture/pull/540.html" title="Last updated on Oct 5, 2020, 2:05 PM UTC (37a6c6e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-architecture/540/466b34c...37a6c6e.html" title="Last updated on Oct 5, 2020, 2:05 PM UTC (37a6c6e)">Diff</a>
=> Add Thing Model text

index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/wot-architecture/pull/563.html" title="Last updated on Oct 15, 2020, 10:16 AM UTC (bed45b0)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-architecture/563/5dc55b1...bed45b0.html" title="Last updated on Oct 15, 2020, 10:16 AM UTC (bed45b0)">Diff</a>
=> Adding changelog

index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/wot-architecture/pull/564.html" title="Last updated on Oct 23, 2020, 2:20 PM UTC (d6358d4)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-architecture/564/bed45b0...d6358d4.html" title="Last updated on Oct 23, 2020, 2:20 PM UTC (d6358d4)">Diff</a>
=> reference to 1.1 specs

index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/wot-architecture/pull/576.html" title="Last updated on Jan 12, 2021, 6:30 PM UTC (da1987d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-architecture/576/591eeb0...da1987d.html" title="Last updated on Jan 12, 2021, 6:30 PM UTC (da1987d)">Diff</a>
=> apply changes for fpwd

index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/wot-architecture/pull/580.html" title="Last updated on Jan 29, 2021, 8:56 AM UTC (b85e070)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-architecture/580/e99dbd6...b85e070.html" title="Last updated on Jan 29, 2021, 8:56 AM UTC (b85e070)">Diff</a>
=> Update index.html - Terminology definition for TD Fragment

index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/wot-architecture/pull/593.html" title="Last updated on Jun 29, 2021, 12:00 PM UTC (18f8269)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-architecture/593/2c6b21e...18f8269.html" title="Last updated on Jun 29, 2021, 12:00 PM UTC (18f8269)">Diff</a>
=> Carry over of device categories from profiles

index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/wot-architecture/pull/645.html" title="Last updated on Nov 26, 2021, 8:32 AM UTC (979e10d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-architecture/645/e2a1cfa...979e10d.html" title="Last updated on Nov 26, 2021, 8:32 AM UTC (979e10d)">Diff</a>
=> improve description of device categories

index.html
fixes #632 #634
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/wot-architecture/pull/654.html" title="Last updated on Dec 16, 2021, 11:12 AM UTC (20792c9)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-architecture/654/a9387b8...20792c9.html" title="Last updated on Dec 16, 2021, 11:12 AM UTC (20792c9)">Diff</a>
=> remove assertations

index.html
fixes  #633
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/wot-architecture/pull/655.html" title="Last updated on Dec 22, 2021, 4:31 PM UTC (373a437)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-architecture/655/8645973...373a437.html" title="Last updated on Dec 22, 2021, 4:31 PM UTC (373a437)">Diff</a>
=> address  #633

index.html
fixes #638
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/wot-architecture/pull/659.html" title="Last updated on Dec 23, 2021, 8:50 AM UTC (a7ee1c4)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-architecture/659/8645973...a7ee1c4.html" title="Last updated on Dec 23, 2021, 8:50 AM UTC (a7ee1c4)">Diff</a>
=> remove assertation arch-op-extension

index.html
Need to have a description of a telemetry system topology in chapter 6
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/wot-architecture/pull/660.html" title="Last updated on Dec 23, 2021, 9:17 AM UTC (6071ad4)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-architecture/660/8645973...6071ad4.html" title="Last updated on Dec 23, 2021, 9:17 AM UTC (6071ad4)">Diff</a>
=> editors note on telemetry

index.html
fixes #639
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/wot-architecture/pull/662.html" title="Last updated on Dec 23, 2021, 9:22 AM UTC (2e7dc99)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-architecture/662/74d1b81...2e7dc99.html" title="Last updated on Dec 23, 2021, 9:22 AM UTC (2e7dc99)">Diff</a>
=> remove arch-uri-scheme

index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/wot-architecture/pull/658.html" title="Last updated on Jan 14, 2022, 4:02 PM UTC (1b2be1d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-architecture/658/8645973...1b2be1d.html" title="Last updated on Jan 14, 2022, 4:02 PM UTC (1b2be1d)">Diff</a>
=> Improve section structure

index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/wot-architecture/pull/665.html" title="Last updated on Dec 23, 2021, 9:51 AM UTC (f5b4bfa)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-architecture/665/8645973...f5b4bfa.html" title="Last updated on Dec 23, 2021, 9:51 AM UTC (f5b4bfa)">Diff</a>
=> placeholder section on orchestration

index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/wot-architecture/pull/667.html" title="Last updated on Dec 23, 2021, 9:52 AM UTC (72ba1a9)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-architecture/667/8645973...72ba1a9.html" title="Last updated on Dec 23, 2021, 9:52 AM UTC (72ba1a9)">Diff</a>
=> adding placeholder section for virtual things

index.html
* Resolves https://github.com/w3c/wot-architecture/issues/672
* Currently a placeholder for WIP - do not merge.
***
<a href="https://pr-preview.s3.amazonaws.com/mmccool/wot-architecture/pull/679.html" title="Last updated on Jan 24, 2022, 2:41 PM UTC (18ac9b5)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-architecture/679/5ca17e0...mmccool:18ac9b5.html" title="Last updated on Jan 24, 2022, 2:41 PM UTC (18ac9b5)">Diff</a>
=> Update Security and Privacy Considerations

index.html
fixes #693
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/wot-architecture/pull/694.html" title="Last updated on Feb 1, 2022, 2:07 PM UTC (7402637)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-architecture/694/c8d1dbb...7402637.html" title="Last updated on Feb 1, 2022, 2:07 PM UTC (7402637)">Diff</a>
=> Improve chapter headings (5&6)

index.html
see https://github.com/w3c/wot-scripting-api/issues/376
***
[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on Feb 28, 2022, 1:27 PM UTC)_.
<details>
<summary>More</summary>
PR Preview relies on a number of web services to run. There seems to be an issue with the following one:
:rotating_light: [Spec Generator](https://www.w3.org/2015/labs/) - Spec Generator is the web service used to build specs that rely on ReSpec.
:link: [Related URL](https://labs.w3.org/spec-generator/?type=respec&url=https%3A%2F%2Fraw.githubusercontent.com%2Fdanielpeintner%2Fwot-architecture-1%2Fb366f73f56de35658946e0d56ec0e65ec6d788eb%2Findex.html%3FisPreview%3Dtrue)
_If you don't have enough information above to solve the error by yourself (or to understand to which web …
=> Align the scripting interfaces in Architecture with the conformance classes in Scripting

index.html
resolves #688
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/wot-architecture/pull/695.html" title="Last updated on Feb 1, 2022, 2:25 PM UTC (e71626f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-architecture/695/7368123...e71626f.html" title="Last updated on Feb 1, 2022, 2:25 PM UTC (e71626f)">Diff</a>
=> fixes #688: Improving language, adding rfc2119 assertion

index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/wot-architecture/pull/731.html" title="Last updated on Apr 7, 2022, 9:58 AM UTC (0fa109a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-architecture/731/e30d299...0fa109a.html" title="Last updated on Apr 7, 2022, 9:58 AM UTC (0fa109a)">Diff</a>
=> fixing issue 616

index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/wot-architecture/pull/730.html" title="Last updated on Apr 7, 2022, 9:42 AM UTC (2f7da09)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-architecture/730/e30d299...2f7da09.html" title="Last updated on Apr 7, 2022, 9:42 AM UTC (2f7da09)">Diff</a>
=> fix respec error on producer

index.html
Closes [661](https://github.com/w3c/wot-architecture/issues/661)
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/wot-architecture/pull/728.html" title="Last updated on Apr 7, 2022, 6:22 AM UTC (b0260ac)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-architecture/728/e30d299...b0260ac.html" title="Last updated on Apr 7, 2022, 6:22 AM UTC (b0260ac)">Diff</a>
=> Draft telemetry section

index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/wot-architecture/pull/740.html" title="Last updated on Apr 28, 2022, 11:14 AM UTC (b22459e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-architecture/740/4e0cc33...b22459e.html" title="Last updated on Apr 28, 2022, 11:14 AM UTC (b22459e)">Diff</a>
=> rename assertions to fit naming conventions

publication/ver11/accessibility.md
of course fixing this will also break all the links to it from issues... argh
=> Fix typo in accessibility.md filename

explainer/explainer11.md
- New discovery section content (main contribution as this was missing before)
- Adding discovery as a building block in the intro
- Adding hyperlinks in Scripting API section to be consistent with other sections
- Adding Scripting and Binding Templates as optional/informative building blocks in the summary
- Changing name "WoT Security and Privacy Considerations" to "WoT Security and Privacy Guidelines"
- Grammatically treating "Security" and "Privacy" as two different things in certain places
- And various other small fixes, including getting rid of some extraneous verbiage and breaking up long sentences.
Note this is a blocker for proceeding with horizontal review.  Please review and I will attempt to deal with any feedback ASAP so we can reach consensus.
=> Explainer Updates 

index.html
Resolves #738
***
<a href="https://pr-preview.s3.amazonaws.com/mmccool/wot-architecture/pull/746.html" title="Last updated on May 12, 2022, 10:25 AM UTC (71bef71)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-architecture/746/7c02a1a...mmccool:71bef71.html" title="Last updated on May 12, 2022, 10:25 AM UTC (71bef71)">Diff</a>
=> Update Discoverer, add Registrant Definitions

index.html
Resolves #697 and #666
This MR also removes editor's notes or converts them to regular notes.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/wot-architecture/pull/750.html" title="Last updated on May 12, 2022, 9:59 AM UTC (9521b03)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-architecture/750/7be810a...9521b03.html" title="Last updated on May 12, 2022, 9:59 AM UTC (9521b03)">Diff</a>
=> adding orchestration section

index.html
resolves #597
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/wot-architecture/pull/751.html" title="Last updated on May 12, 2022, 10:47 AM UTC (b40169f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-architecture/751/7be810a...b40169f.html" title="Last updated on May 12, 2022, 10:47 AM UTC (b40169f)">Diff</a>
=> improving profile description

index.html
resolves #752
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/wot-architecture/pull/754.html" title="Last updated on May 18, 2022, 1:30 PM UTC (9781d7e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-architecture/754/36ad1c9...9781d7e.html" title="Last updated on May 18, 2022, 1:30 PM UTC (9781d7e)">Diff</a>
=> terminology for orchestration

index.html
resolves #664
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/wot-architecture/pull/761.html" title="Last updated on May 19, 2022, 10:28 AM UTC (7365a71)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-architecture/761/36ad1c9...7365a71.html" title="Last updated on May 19, 2022, 10:28 AM UTC (7365a71)">Diff</a>
=> replacing placeholder for virtual thing with content

index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/wot-architecture/pull/762.html" title="Last updated on May 19, 2022, 9:56 AM UTC (205c968)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-architecture/762/36ad1c9...205c968.html" title="Last updated on May 19, 2022, 9:56 AM UTC (205c968)">Diff</a>
=> changing table style

index.html
"TD Server", short for "Thing Description Server", it a new term used in Discovery to describe an endpoint that can return a Thing Description when accessed.  
This PR adds "TD Server" and "Thing Description Server" to the Terminology section.  These are not used in Architecture but in WoT Discovery, but we want to consolidate terminology definitions in WoT Architecture.
***
[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on Jun 17, 2022, 4:45 PM UTC)_.
<details>
<summary>More</summary>
PR Preview relies on a number of web services to run. There seems to be an issue with the following one:
:rotating_light: [HTML Diff Service](http://services.w3.org/htmldiff) - The HTML Diff Service is used to create HTML diffs of the spec changes suggested in a …
=> Define TD Server

index.html
solves #608
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/wot-architecture/pull/784.html" title="Last updated on Jun 30, 2022, 10:40 AM UTC (1c68074)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-architecture/784/af14f99...1c68074.html" title="Last updated on Jun 30, 2022, 10:40 AM UTC (1c68074)">Diff</a>
=> Intro text for the binding template section

index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/wot-architecture/pull/787.html" title="Last updated on Jul 3, 2022, 5:09 PM UTC (e68a64e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-architecture/787/0b1117c...e68a64e.html" title="Last updated on Jul 3, 2022, 5:09 PM UTC (e68a64e)">Diff</a>
=> Text improvements to Introduction and Terminology

index.html
editorial improvements: markup, minor text changes
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/wot-architecture/pull/789.html" title="Last updated on Jul 3, 2022, 6:50 PM UTC (e459d7f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-architecture/789/0b1117c...e459d7f.html" title="Last updated on Jul 3, 2022, 6:50 PM UTC (e459d7f)">Diff</a>
=> Editorial fixes to chapter 6

index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/wot-architecture/pull/793.html" title="Last updated on Jul 4, 2022, 9:10 PM UTC (971a203)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-architecture/793/0b1117c...971a203.html" title="Last updated on Jul 4, 2022, 9:10 PM UTC (971a203)">Diff</a>
=> additional editor: Michael McCool

index.html
editorial improvements, section ids
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/wot-architecture/pull/791.html" title="Last updated on Jul 4, 2022, 6:57 AM UTC (92171eb)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-architecture/791/0b1117c...92171eb.html" title="Last updated on Jul 4, 2022, 6:57 AM UTC (92171eb)">Diff</a>
=> Updates to chapter 8

index.html
resolves #620
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/wot-architecture/pull/798.html" title="Last updated on Jul 4, 2022, 8:51 PM UTC (dd1f322)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-architecture/798/0b1117c...dd1f322.html" title="Last updated on Jul 4, 2022, 8:51 PM UTC (dd1f322)">Diff</a>
=> i18n section

index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/wot-architecture/pull/792.html" title="Last updated on Aug 4, 2022, 9:21 AM UTC (a9a9777)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-architecture/792/0b1117c...a9a9777.html" title="Last updated on Aug 4, 2022, 9:21 AM UTC (a9a9777)">Diff</a>
=> Chapter 9: editorial fixes

index.html
Adding proposed language from #591.
Closes #591
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/wot-architecture/pull/799.html" title="Last updated on Jul 21, 2022, 8:52 AM UTC (86b7b1b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-architecture/799/0b1117c...86b7b1b.html" title="Last updated on Jul 21, 2022, 8:52 AM UTC (86b7b1b)">Diff</a>
=> Clarifications on discovery

index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/wot-architecture/pull/831.html" title="Last updated on Sep 8, 2022, 2:31 PM UTC (585a1ed)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-architecture/831/2d1f901...585a1ed.html" title="Last updated on Sep 8, 2022, 2:31 PM UTC (585a1ed)">Diff</a>
=> fixing respec problems

publication/ver11/3-cr/Overview.html, publication/ver11/3-cr/index.html, publication/ver11/3-cr/static.html
=> Even More CR Preparation

publication/ver11/3-cr/Overview.html, publication/ver11/3-cr/index.html, publication/ver11/3-cr/static.html
- revert to CR Snapshot, CRD seems broken, other changes to make pubrules happier
=> More and More CR preparation

index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/wot-architecture/pull/838.html" title="Last updated on Sep 13, 2022, 9:35 AM UTC (1b5d06e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-architecture/838/a2c6698...1b5d06e.html" title="Last updated on Sep 13, 2022, 9:35 AM UTC (1b5d06e)">Diff</a>
=> Minor typos

index.html
***
<a href="https://pr-preview.s3.amazonaws.com/mmccool/wot-architecture/pull/843.html" title="Last updated on Sep 22, 2022, 10:37 AM UTC (318d86d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-architecture/843/df6692c...mmccool:318d86d.html" title="Last updated on Sep 22, 2022, 10:37 AM UTC (318d86d)">Diff</a>
=> Add definition for Directory

testing/inputs/templates/report.html, testing/report11.html
- Update "planned dates" for publications
=> WIP: Aug 2022 impl report update - 2

index.html
solves #841
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/wot-architecture/pull/847.html" title="Last updated on Sep 29, 2022, 8:24 AM UTC (0ac0328)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-architecture/847/0287019...0ac0328.html" title="Last updated on Sep 29, 2022, 8:24 AM UTC (0ac0328)">Diff</a>
=> Update Security Link

testing/manual.csv, testing/report11.html
- make manual.csv a copy of template.csv (since everything is currently manual) 
- note that this CSV file is referenced from wot-testing for the Dec 2022 testfest
=> Testing CSV cleanup

publication/ver11/societal_impact.md
- Answers are meant to apply to all WoT specs, but put under Architecture as this is how we have dealt with similar global concerns.
=> Societal Impact Questionniare

index.html
Resolves #864 
Change "native" to "low-level hardware" to be clearer
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/wot-architecture/pull/912.html" title="Last updated on May 18, 2023, 10:48 AM UTC (4a7619e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-architecture/912/184a144...4a7619e.html" title="Last updated on May 18, 2023, 10:48 AM UTC (4a7619e)">Diff</a>
=> Revise native to low-level hardware

testing/inputs/implementations/fujitsu-ledbulb.html, testing/inputs/implementations/fujitsu-proxy.html, testing/inputs/implementations/fujitsu-sensor.html, testing/inputs/implementations/hitachi-espidf.html, testing/inputs/implementations/hitachi-nodegen.html, testing/inputs/implementations/hitachi-nodered.html, testing/inputs/implementations/hitachi-nrwotdisc.html, testing/inputs/implementations/intel-nodejs.html, testing/inputs/implementations/intel-proxy.html, testing/inputs/implementations/intel-wot-ha.html, testing/inputs/implementations/philips-hue.html, testing/inputs/implementations/python-flask-custom.html, testing/inputs/implementations/sdf-wot-converter.html, testing/inputs/implementations/siemens-logilab.html, testing/inputs/implementations/tinyiot.html, testing/inputs/implementations/wot-coap-dns-sd.html, testing/inputs/implementations/wot-experimental.html, testing/inputs/implementations/zion.html, testing/inputs/templates/cr-report.html, testing/inputs/templates/report.html, testing/report11.html
- update template, fixing various small issues, making consistent with TD and Discovery
- update language so it relates to PR, not CR (CR period becomes past tense, etc)
- update implementation descriptions
- update copyright and acknowledgements
- no changes to assertion status
=> Update Implementation Report

testing/inputs/templates/report.html, testing/report11.html
- Remove "DRAFT" from title
- Use "Kaebisch" spelling of Sebastian's name (without umlaut) for consistency
=> Implementation Report Cleanup for PR

index.html, publication/ver11/5-rec/Overview.html, publication/ver11/5-rec/index.html, publication/ver11/5-rec/static.html
Final; fix Panasonic Corp reference.
***
<a href="https://pr-preview.s3.amazonaws.com/mmccool/wot-architecture/pull/938.html" title="Last updated on Oct 24, 2023, 6:19 PM UTC (8712265)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-architecture/938/cef7251...mmccool:8712265.html" title="Last updated on Oct 24, 2023, 6:19 PM UTC (8712265)">Diff</a>
=> REC Preparation v3
